[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "ownscripts"
version = "0.1.0"
description = "Library for my own python scripts"
readme = "README.md"
requires-python = ">=3.8"


[tool.setuptools.packages.find]
include = [
    "ownscripts",
    ]
